<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('precios', function (Blueprint $table) {
            $table->id();
            $table->foreignId('producto_caracteristica_id') 
                ->references('id')
                ->on('producto_caracteristicas')
                ->onUpdate('no action')
                ->onDelete('no action');
            $table->integer('desde');
            $table->integer('hasta');
            $table->integer('porcentaje_publico')->nullable();
            $table->integer('porcentaje_medio')->nullable();
            $table->integer('porcentaje_mayoreo')->nullable();
            $table->integer('especifico_publico')->nullable();
            $table->integer('especifico_medio')->nullable();
            $table->integer('especifico_mayoreo')->nullable();
            $table->string('precio'); //INTERNO, CVA, GLOMA ETC
            $table->boolean('tipo_precio')->default(1); // 1 = General; 2 = Especifico
            $table->boolean('activo')->default(1);
            $table->timestamps();
        });

        DB::table("precios")
            ->insert([
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 1,
                    'hasta' => 8,
                    'porcentaje_publico' => 85.00,
                    'porcentaje_medio' => 70.00,
                    'porcentaje_mayoreo' => 58.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 9,
                    'hasta' => 12,
                    'porcentaje_publico' => 75.00,
                    'porcentaje_medio' => 65.00,
                    'porcentaje_mayoreo' => 56.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 13,
                    'hasta' => 18,
                    'porcentaje_publico' => 65.00,
                    'porcentaje_medio' => 52.00,
                    'porcentaje_mayoreo' => 45.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 19,
                    'hasta' => 25,
                    'porcentaje_publico' => 50.00,
                    'porcentaje_medio' => 35.00,
                    'porcentaje_mayoreo' => 30.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 26,
                    'hasta' => 35,
                    'porcentaje_publico' => 45.00,
                    'porcentaje_medio' => 33.00,
                    'porcentaje_mayoreo' => 21.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 36,
                    'hasta' => 45,
                    'porcentaje_publico' => 40.00,
                    'porcentaje_medio' => 22.00,
                    'porcentaje_mayoreo' => 18.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 46,
                    'hasta' => 59,
                    'porcentaje_publico' => 35.00,
                    'porcentaje_medio' => 20.00,
                    'porcentaje_mayoreo' => 16.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 60,
                    'hasta' => 79,
                    'porcentaje_publico' => 30.00,
                    'porcentaje_medio' => 18.00,
                    'porcentaje_mayoreo' => 15.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 80,
                    'hasta' => 100,
                    'porcentaje_publico' => 25.00,
                    'porcentaje_medio' => 16.00,
                    'porcentaje_mayoreo' => 13.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 101,
                    'hasta' => 125,
                    'porcentaje_publico' => 23.00,
                    'porcentaje_medio' => 14.00,
                    'porcentaje_mayoreo' => 12.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 126,
                    'hasta' => 160,
                    'porcentaje_publico' => 22.00,
                    'porcentaje_medio' => 14.00,
                    'porcentaje_mayoreo' => 12.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 161,
                    'hasta' => 200,
                    'porcentaje_publico' => 21.00,
                    'porcentaje_medio' => 13.00,
                    'porcentaje_mayoreo' => 11.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 201,
                    'hasta' => 260,
                    'porcentaje_publico' => 19.00,
                    'porcentaje_medio' => 12.00,
                    'porcentaje_mayoreo' => 10.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 261,
                    'hasta' => 300,
                    'porcentaje_publico' => 17.00,
                    'porcentaje_medio' => 10.50,
                    'porcentaje_mayoreo' => 9.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 15:53:21'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 301,
                    'hasta' => 350,
                    'porcentaje_publico' => 15.00,
                    'porcentaje_medio' => 10.50,
                    'porcentaje_mayoreo' => 9.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:01:24'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 351,
                    'hasta'=>  400,
                    'porcentaje_publico' => 13.50,
                    'porcentaje_medio' => 9.50,
                    'porcentaje_mayoreo' => 8.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:02:06'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 401,
                    'hasta'=>  460,
                    'porcentaje_publico' => 13.00,
                    'porcentaje_medio' => 9.00,
                    'porcentaje_mayoreo' => 7.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:02:43'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 461,
                    'hasta'=>  550,
                    'porcentaje_publico' => 12.00,
                    'porcentaje_medio' => 8.50,
                    'porcentaje_mayoreo' => 7.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:03:17'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 551,
                    'hasta'=> 630,
                    'porcentaje_publico' => 11.00,
                    'porcentaje_medio' => 8.00,
                    'porcentaje_mayoreo' => 6.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:03:42'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 631,
                    'hasta'=>  730,
                    'porcentaje_publico' => 10.00,
                    'porcentaje_medio' => 7.50,
                    'porcentaje_mayoreo' => 6.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:04:34'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 731,
                    'hasta'=>  850,
                    'porcentaje_publico' => 9.50, 
                    'porcentaje_medio' =>7.50,
                    'porcentaje_mayoreo' => 6.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:05:11'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 851,
                    'hasta'=>  1000,
                    'porcentaje_publico' => 10.00,
                    'porcentaje_medio' => 7.50,
                    'porcentaje_mayoreo' => 6.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:05:49'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 1001,
                    'hasta'=>  1500,
                    'porcentaje_publico' => 10.00,
                    'porcentaje_medio' => 7.50,
                    'porcentaje_mayoreo' => 6.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:06:24'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 1501,
                    'hasta'=>  2000,
                    'porcentaje_publico' => 10.00,
                    'porcentaje_medio' => 7.50,
                    'porcentaje_mayoreo' => 6.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:07:25'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 2001,
                    'hasta'=>  2500,
                    'porcentaje_publico' => 9.50, 
                    'porcentaje_medio' =>7.00,
                    'porcentaje_mayoreo' => 5.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:08:10'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 2501,
                    'hasta'=>  3300,
                    'porcentaje_publico' => 9.00, 
                    'porcentaje_medio' =>6.50,
                    'porcentaje_mayoreo' => 5.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:08:57'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 3301,
                    'hasta'=>  4300,
                    'porcentaje_publico' => 8.00, 
                    'porcentaje_medio' =>6.00,
                    'porcentaje_mayoreo' => 4.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:09:29'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 4301,
                    'hasta'=>  5000,
                    'porcentaje_publico' => 7.50, 
                    'porcentaje_medio' =>6.00,
                    'porcentaje_mayoreo' => 4.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:10:53'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 5001,
                    'hasta'=>  6500,
                    'porcentaje_publico' => 7.50, 
                    'porcentaje_medio' =>5.50,
                    'porcentaje_mayoreo' => 4.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:11:29'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 6501,
                    'hasta'=>  7500,
                    'porcentaje_publico' => 7.00, 
                    'porcentaje_medio' =>5.00,
                    'porcentaje_mayoreo' => 4.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 7501,
                    'hasta'=>  10000,
                    'porcentaje_publico' => 6.50, 
                    'porcentaje_medio' =>4.50,
                    'porcentaje_mayoreo' => 3.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:12:28'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 10001,
                    'hasta'=>  15000,
                    'porcentaje_publico' => 6.00, 
                    'porcentaje_medio' =>4.20,
                    'porcentaje_mayoreo' => 3.30, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:13:25'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 15001,
                    'hasta'=>  25000,
                    'porcentaje_publico' => 6.00, 
                    'porcentaje_medio' =>4.00,
                    'porcentaje_mayoreo' => 3.00, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 05:54:59'
                ],
                [ 'producto_caracteristica_id' => 3,
                    'desde' => 25001,
                    'hasta'=>  50000,
                    'porcentaje_publico' => 5.50, 
                    'porcentaje_medio' =>3.60,
                    'porcentaje_mayoreo' => 2.50, 
                    'especifico_publico' => null,
                    'especifico_medio' =>null,
                    'especifico_mayoreo' => null,
                    'precio' => 'INTERNO',
                    'tipo_precio' => 1,
                    'activo' => 1,
                    'created_at' => '2024-05-07 05:54:59',
                    'updated_at' => '2024-05-07 16:13:59'
                ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('precios');
    }
};
